// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcLtt3EJrz1SXXmtLVSvoSgz4BKqFzARQ',
    appId: '1:139274726264:web:3a580e6225f7c0f1f9b68d',
    messagingSenderId: '139274726264',
    projectId: 'spotify-clone-capslock',
    authDomain: 'spotify-clone-capslock.firebaseapp.com',
    storageBucket: 'spotify-clone-capslock.appspot.com',
    measurementId: 'G-113530YT63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYb8zTzHOFdap6V6ekE7CbGxoPMyH6Va0',
    appId: '1:139274726264:android:dcf26ff755be2cd6f9b68d',
    messagingSenderId: '139274726264',
    projectId: 'spotify-clone-capslock',
    storageBucket: 'spotify-clone-capslock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCozcowaZ3u6xzLvw5_Rkvx7NptoO3eZDs',
    appId: '1:139274726264:ios:fdc1035b6a00c8acf9b68d',
    messagingSenderId: '139274726264',
    projectId: 'spotify-clone-capslock',
    storageBucket: 'spotify-clone-capslock.appspot.com',
    iosClientId: '139274726264-f7usi0d57hst2n1f0idk39rn7u49oth3.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCozcowaZ3u6xzLvw5_Rkvx7NptoO3eZDs',
    appId: '1:139274726264:ios:ecc0d78f08496235f9b68d',
    messagingSenderId: '139274726264',
    projectId: 'spotify-clone-capslock',
    storageBucket: 'spotify-clone-capslock.appspot.com',
    iosClientId: '139274726264-637f9qa1sf1t51g24m8s35vu89g635mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone.RunnerTests',
  );
}
