// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj1ojGvNVPsRbJ41C9GFeXk3HITd0p6nY',
    appId: '1:759364394351:android:c65f5849c4fedb4da4dc9a',
    messagingSenderId: '759364394351',
    projectId: 'toasties-kitahack-2024',
    storageBucket: 'toasties-kitahack-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3f39_01wrfIm0iC7TBRTXl9IhBgTAW-k',
    appId: '1:759364394351:ios:f8daa2a6e95f9e13a4dc9a',
    messagingSenderId: '759364394351',
    projectId: 'toasties-kitahack-2024',
    storageBucket: 'toasties-kitahack-2024.appspot.com',
    androidClientId: '759364394351-2k91dsf3mfo2k7hd4b8d887hqkp0u1tt.apps.googleusercontent.com',
    iosClientId: '759364394351-9v5c5cdb8us63slqu3l21u2ale58hju3.apps.googleusercontent.com',
    iosBundleId: 'com.example.toastiesFlutter',
  );
}
